# Generated by Django 3.2 on 2021-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_source', models.CharField(blank=True, max_length=32, null=True)),
                ('art_url', models.CharField(blank=True, max_length=255, null=True)),
                ('art_title', models.CharField(blank=True, max_length=255, null=True)),
                ('art_content', models.TextField(blank=True, null=True)),
                ('art_type', models.CharField(blank=True, max_length=32, null=True)),
                ('art_image', models.CharField(blank=True, max_length=255, null=True)),
                ('art_time', models.DateTimeField(blank=True, null=True)),
                ('art_legal', models.IntegerField(blank=True, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_idx', models.CharField(blank=True, max_length=255, null=True)),
                ('relation_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tfidf',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=32, null=True)),
                ('word_idf', models.FloatField(blank=True, null=True)),
                ('word_col', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'tfidf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=64, null=True)),
                ('user_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('user_gender', models.IntegerField(blank=True, null=True)),
                ('user_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('user_create_time', models.DateTimeField(blank=True, null=True)),
                ('user_last_login_time', models.DateTimeField(blank=True, null=True)),
                ('user_legal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('behavior', models.IntegerField(blank=True, null=True)),
                ('behavior_time', models.DateTimeField(blank=True, null=True)),
                ('art_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_log',
                'managed': True,
            },
        ),
    ]
